export const browserCoreExamples = [
  "mechanical-wings browser status",
  "mechanical-wings browser start",
  "mechanical-wings browser stop",
  "mechanical-wings browser tabs",
  "mechanical-wings browser open https://example.com",
  "mechanical-wings browser focus abcd1234",
  "mechanical-wings browser close abcd1234",
  "mechanical-wings browser screenshot",
  "mechanical-wings browser screenshot --full-page",
  "mechanical-wings browser screenshot --ref 12",
  "mechanical-wings browser snapshot",
  "mechanical-wings browser snapshot --format aria --limit 200",
  "mechanical-wings browser snapshot --efficient",
  "mechanical-wings browser snapshot --labels",
];

export const browserActionExamples = [
  "mechanical-wings browser navigate https://example.com",
  "mechanical-wings browser resize 1280 720",
  "mechanical-wings browser click 12 --double",
  'mechanical-wings browser type 23 "hello" --submit',
  "mechanical-wings browser press Enter",
  "mechanical-wings browser hover 44",
  "mechanical-wings browser drag 10 11",
  "mechanical-wings browser select 9 OptionA OptionB",
  "mechanical-wings browser upload /tmp/mechanical-wings/uploads/file.pdf",
  'mechanical-wings browser fill --fields \'[{"ref":"1","value":"Ada"}]\'',
  "mechanical-wings browser dialog --accept",
  'mechanical-wings browser wait --text "Done"',
  "mechanical-wings browser evaluate --fn '(el) => el.textContent' --ref 7",
  "mechanical-wings browser console --level error",
  "mechanical-wings browser pdf",
];
