apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mechanical-wings-home-pvc
  labels:
    app: mechanical-wings
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
